import { Icon } from '../plugin';

const IconList: Icon[] = [
  {
    description: 'any rune type',
    icon: 'any',
    category: 'Rules Indicator',
    tags: ['rainbow', 'rune', 'any', 'generic'],
  },
  {
    description: 'battlefield card type',
    icon: 'battlefield',
    category: 'Card Type',
    tags: ['battleground', 'tower'],
  },
  {
    description: 'simple calm rune type',
    icon: 'calm',
    category: 'Rune Type',
    tags: ['calm', 'simple', 'power'],
  },
  {
    description: 'colored calm rune type',
    icon: 'calm_color',
    category: 'Rune Type',
    tags: ['calm', 'color', 'power'],
  },
  {
    description: 'complex calm rune type',
    icon: 'calm_complex',
    category: 'Rune Type',
    tags: ['calm', 'complex', 'power'],
  },
  {
    description: 'complete calm rune type',
    icon: 'calm_complete',
    category: 'Rune Type',
    tags: ['calm', 'complete', 'power'],
  },
  {
    description: 'champion card type',
    icon: 'champion',
    category: 'Card Type',
    tags: ['champion', 'hero'],
  },
  {
    description: 'simple chaos rune type',
    icon: 'chaos',
    category: 'Rune Type',
    tags: ['chaos', 'simple', 'power'],
  },
  {
    description: 'colored chaos rune type',
    icon: 'chaos_color',
    category: 'Rune Type',
    tags: ['chaos', 'color', 'power'],
  },
  {
    description: 'complex chaos rune type',
    icon: 'chaos_complex',
    category: 'Rune Type',
    tags: ['chaos', 'complex', 'power'],
  },
  {
    description: 'complete chaos rune type',
    icon: 'chaos_complete',
    category: 'Rune Type',
    tags: ['chaos', 'complete', 'power'],
  },
  {
    description: 'zero energy cost indicator',
    icon: 'cost0',
    category: 'Rules Indicator',
    tags: ['cost', 'free', 'energy'],
  },
  {
    description: 'one energy cost indicator',
    icon: 'cost1',
    category: 'Rules Indicator',
    tags: ['cost', 'one', 'energy'],
  },
  {
    description: 'two energy cost indicator',
    icon: 'cost2',
    category: 'Rules Indicator',
    tags: ['cost', 'two', 'energy'],
  },
  {
    description: 'three energy cost indicator',
    icon: 'cost3',
    category: 'Rules Indicator',
    tags: ['cost', 'three', 'energy'],
  },
  {
    description: 'four energy cost indicator',
    icon: 'cost4',
    category: 'Rules Indicator',
    tags: ['cost', 'four', 'energy'],
  },
  {
    description: 'five energy cost indicator',
    icon: 'cost5',
    category: 'Rules Indicator',
    tags: ['cost', 'five', 'energy'],
  },
  {
    description: 'six energy cost indicator',
    icon: 'cost6',
    category: 'Rules Indicator',
    tags: ['cost', 'six', 'energy'],
  },
  {
    description: 'seven energy cost indicator',
    icon: 'cost7',
    category: 'Rules Indicator',
    tags: ['cost', 'seven', 'energy'],
  },
  {
    description: 'eight energy cost indicator',
    icon: 'cost8',
    category: 'Rules Indicator',
    tags: ['cost', 'eight', 'energy'],
  },
  {
    description: 'nine energy cost indicator',
    icon: 'cost9',
    category: 'Rules Indicator',
    tags: ['cost', 'nine', 'energy'],
  },
  {
    description: 'ten energy cost indicator',
    icon: 'cost10',
    category: 'Rules Indicator',
    tags: ['cost', 'ten', 'energy'],
  },
  {
    description: 'eleven energy cost indicator',
    icon: 'cost11',
    category: 'Rules Indicator',
    tags: ['cost', 'eleven', 'energy'],
  },
  {
    description: 'exhaust indicator',
    icon: 'exhaust',
    category: 'Rules Indicator',
    tags: ['tap', 'exhaust', 'rest', 'exert'],
  },
  {
    description: 'simple fury rune type',
    icon: 'fury',
    category: 'Rune Type',
    tags: ['fury', 'simple', 'power'],
  },
  {
    description: 'colored fury rune type',
    icon: 'fury_color',
    category: 'Rune Type',
    tags: ['fury', 'color', 'power'],
  },
  {
    description: 'complex fury rune type',
    icon: 'fury_complex',
    category: 'Rune Type',
    tags: ['fury', 'complex', 'power'],
  },
  {
    description: 'complete fury rune type',
    icon: 'fury_complete',
    category: 'Rune Type',
    tags: ['fury', 'complete', 'power'],
  },
  {
    description: 'gear card type indicator',
    icon: 'gear',
    category: 'Card Type',
    tags: ['equipment'],
  },
  {
    description: 'legend card type indicator',
    icon: 'legend',
    category: 'Card Type',
    tags: ['legend', 'hero', 'character', 'commander'],
  },
  {
    description: 'simple mental rune type',
    icon: 'mental',
    category: 'Rune Type',
    tags: ['mental', 'simple', 'power'],
  },
  {
    description: 'colored mental rune type',
    icon: 'mental_color',
    category: 'Rune Type',
    tags: ['mental', 'color', 'power'],
  },
  {
    description: 'complex mental rune type',
    icon: 'mental_complex',
    category: 'Rune Type',
    tags: ['mental', 'complex', 'power'],
  },
  {
    description: 'complete mental rune type',
    icon: 'mental_complete',
    category: 'Rune Type',
    tags: ['mental', 'complete', 'power'],
  },
  {
    description: 'card power/toughness indicator',
    icon: 'might',
    category: 'Rules Indicator',
    tags: ['might', 'power', 'toughness', 'attack', 'strength'],
  },
  {
    description: 'simple order rune type',
    icon: 'order',
    category: 'Rune Type',
    tags: ['order', 'simple', 'power'],
  },
  {
    description: 'colored order rune type',
    icon: 'order_color',
    category: 'Rune Type',
    tags: ['order', 'color', 'power'],
  },
  {
    description: 'complex order rune type',
    icon: 'order_complex',
    category: 'Rune Type',
    tags: ['order', 'complex', 'power'],
  },
  {
    description: 'complete order rune type',
    icon: 'order_complete',
    category: 'Rune Type',
    tags: ['order', 'complete', 'power'],
  },
  {
    description: 'simple physical rune type',
    icon: 'physical',
    category: 'Rune Type',
    tags: ['physical', 'simple', 'power'],
  },
  {
    description: 'colored physical rune type',
    icon: 'physical_color',
    category: 'Rune Type',
    tags: ['physical', 'color', 'power'],
  },
  {
    description: 'complex physical rune type',
    icon: 'physical_complex',
    category: 'Rune Type',
    tags: ['physical', 'complex', 'power'],
  },
  {
    description: 'complete physical rune type',
    icon: 'physical_complete',
    category: 'Rune Type',
    tags: ['physical', 'complete', 'power'],
  },
  {
    description: 'generic rune indicator',
    icon: 'rune',
    category: 'Rules Indicator',
    tags: ['rune', 'power', 'generic'],
  },
  {
    description: 'spell card type indicator',
    icon: 'spell',
    category: 'Card Type',
    tags: ['spell', 'reaction', 'instant'],
  },
  {
    description: 'unit card type indicator',
    icon: 'unit',
    category: 'Card Type',
    tags: ['unit', 'monster', 'minion', 'creature'],
  },
];

export default IconList;
